In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(r'C:\Users\lenovo\OneDrive\Desktop\deep-learning\datasets\student_performance_dataset.csv')

In [4]:
df.head()

,Student_ID,Gender,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Parental_Education_Level,Internet_Access_at_Home,Extracurricular_Activities,Final_Exam_Score,Pass_Fail
0,S147,Male,31,68.267841,86,High School,Yes,Yes,63,Pass
1,S136,Male,16,78.222927,73,PhD,No,No,50,Fail
2,S209,Female,21,87.525096,74,PhD,Yes,No,55,Fail
3,S458,Female,27,92.076483,99,Bachelors,No,No,65,Pass
4,S078,Female,37,98.655517,63,Masters,No,Yes,70,Pass

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 708 entries, 0 to 707
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  708 non-null    object
 1   Gender                      708 non-null    object
 2   Study_Hours_per_Week        708 non-null    int64
 3   Attendance_Rate             708 non-null    float64
 4   Past_Exam_Scores            708 non-null    int64
 5   Parental_Education_Level    708 non-null    object
 6   Internet_Access_at_Home     708 non-null    object
 7   Extracurricular_Activities  708 non-null    object
 8   Final_Exam_Score            708 non-null    int64
 9   Pass_Fail                   708 non-null    object
dtypes: float64(1), int64(3), object(6)
memory usage: 55.4+ KB

In [6]:
df.isnull().sum()

Student_ID                    0
Gender                        0
Study_Hours_per_Week          0
Attendance_Rate               0
Past_Exam_Scores              0
Parental_Education_Level      0
Internet_Access_at_Home       0
Extracurricular_Activities    0
Final_Exam_Score              0
Pass_Fail                     0
dtype: int64

In [7]:
df = df.drop(['Student_ID', 'Gender'], axis=1)

In [8]:
df.head()

,Study_Hours_per_Week,Attendance_Rate,Past_Exam_Scores,Parental_Education_Level,Internet_Access_at_Home,Extracurricular_Activities,Final_Exam_Score,Pass_Fail
0,31,68.267841,86,High School,Yes,Yes,63,Pass
1,16,78.222927,73,PhD,No,No,50,Fail
2,21,87.525096,74,PhD,Yes,No,55,Fail
3,27,92.076483,99,Bachelors,No,No,65,Pass
4,37,98.655517,63,Masters,No,Yes,70,Pass

In [9]:
df['Pass_Fail'] = df['Pass_Fail'].map({'pass':1, 'fail':0})

In [11]:
df['Pass_Fail']

0     NaN
1     NaN
2     NaN
3     NaN
4     NaN
       ..
703   NaN
704   NaN
705   NaN
706   NaN
707   NaN
Name: Pass_Fail, Length: 708, dtype: float64

In [ ]:
col_cat = df([
    'Internet_Access_at_Home',
    'Extracurricular_Activities'
])